config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    member do
      post :vote_up, :vote_down, :vote_undo
    end
  end
  root 'posts#index'
  get 'home/about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_voteable
  belongs_to :user
  has_attached_file :image,:path => ':rails_root/public/system/abstracts/:attachment/:filename',
                    :url => '/system/abstracts/:attachment/:filename', :style => {:large => "750x750", :medium => "300x300>", :thumb =>"100x100>"}
  validates_attachment_content_type :image, :content_type => %w(image/jpg image/jpeg image/png image/gif image/webp), present:true

end

app/models/user.rb
class User < ApplicationRecord
  acts_as_voter
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts

end

app/models/vote.rb
class Vote < ActiveRecord::Base

  scope :for_voter, lambda { |*args| where(["voter_id = ? AND voter_type = ?", args.first.id, args.first.class.base_class.name]) }
  scope :for_voteable, lambda { |*args| where(["voteable_id = ? AND voteable_type = ?", args.first.id, args.first.class.base_class.name]) }
  scope :recent, lambda { |*args| where(["created_at > ?", (args.first || 2.weeks.ago)]) }
  scope :descending, lambda { order("created_at DESC") }

  belongs_to :voteable, :polymorphic => true
  belongs_to :voter, :polymorphic => true

  attr_accessible :vote, :voter, :voteable if ActiveRecord::VERSION::MAJOR < 4


  # Comment out the line below to allow multiple votes per user.
  validates_uniqueness_of :voteable_id, :scope => [:voteable_type, :voter_type, :voter_id]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 20)
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  def vote_up
    begin
      postt=@post = Post.find(params[:id])
      current_user.unvote_for(postt)
      current_user.vote_for(postt)
      flash[:notice] = "Upvoted!"
      redirect_to "/posts"
    rescue ActiveRecord::RecordInvalid
      flash[:notice] = "Error has occured!"
      redirect_to "/posts"
    end
  end

  def vote_down
    begin
      postt=@post = Post.find(params[:id])
      current_user.unvote_for(postt)
      current_user.vote_against(postt)
      flash[:notice] = "Down voted!"
      redirect_to "/posts"
    rescue ActiveRecord::RecordInvalid
      flash[:notice] = "Error has occured!"
      redirect_to "/posts"
    end
  end
  def vote_undo
    begin
      postt=@post = Post.find(params[:id])
      current_user.unvote_for(postt)
      flash[:notice] = "Unvoted!"
      redirect_to "/posts"
    rescue ActiveRecord::RecordInvalid
      flash[:notice] = "Error has occured!"
      redirect_to "/posts"
    end
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)


    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:description, :image, :name)
    end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])

  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/_footer.html.erb
<div class="footer box-footer boxbg">
  <p><%= simple_format "All rights reserved © 2020 - #{Date.today.year}"  %></p>
</div>

app/views/home/_header.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<nav class="navbar navbar-fixed-top navbar-dark bg-gradient-dark">
  <div class="navbar-nav navbarcustom " id="navbar1">
    <%= link_to (inline_svg_tag("logo.svg", options={class:'logo', nocomment: true, title: "4laugh"})), root_path, class:'navbar-brand custombrand verticalalign'%>
    <li class="nav-item active verticalalign">
      <%= link_to 'Home', root_path, class:'btn btn-primary' %>
    </li>
    <li class="nav-item verticalalign">
      <%= link_to 'About', home_about_path, class:'btn btn-default' %>
    </li>
    <%if user_signed_in? %>
      <li class="nav-item verticalalign">
        <%= link_to 'Edit profile', edit_user_registration_path, class:'btn btn-default' %>
      </li><li class="nav-item verticalalign">
    <%= link_to 'Log out', destroy_user_session_path, class:'btn btn-default', method: :delete %>
  </li>
      <li class="nav-item verticalalign">
        <%= link_to 'New post', new_post_path, class:'btn btn-default'%>
      </li>
      <% else %>
    <li class="nav-item verticalalign">
      <%= link_to 'Log in', new_user_session_path, class:'btn btn-default' %>
    </li>
      <li class="nav-item verticalalign">
    <%= link_to 'Sign up', new_user_registration_path, class:'btn btn-default' %>
        <% end %>
  </li>


    <div class="btn-group-toggle align-self-end custom2" data-toggle="buttons" id="navbar3" >
      <label class="btn btn-secondary">
        <input type="radio" name="options" id="brightness" checked="checked" > Light
      </label>
      <label class="btn btn-secondary">
        <input type="radio" name="options" id="brightness2"> Dark
      </label>
    </div>

  </div>
</nav>

<script>
    $(document).ready(function () {
        mycolor = localStorage.getItem("colour");
        fontcolor = localStorage.getItem("text-colour");
        boxcolor= localStorage.getItem("box");
        buttoncolor= localStorage.getItem("button");
        $("body").css("background", mycolor);
        $("body").css("color", fontcolor);
        $(".boxbg").css("background", boxcolor);
        $(".buttonbg").css("background", buttoncolor);
        $('#brightness').click(function () {
            mycolor = '#bebebe';
            fontcolor = '#000';
            boxcolor = '#b0b0b0';
            buttoncolor = '#e3e3e3';
            $("body").css("background", mycolor);
            $("body").css("color", fontcolor);
            $(".boxbg").css("background", boxcolor);
            $(".buttonbg").css("background", buttoncolor);
            localStorage.setItem("colour", mycolor);
            localStorage.setItem("text-colour", fontcolor);
            localStorage.setItem("box",boxcolor);
            localStorage.setItem("button", buttoncolor);
        });
        $('#brightness2').click(function () {
            mycolor = "#272727";
            fontcolor = '#CCC';
            boxcolor = '#171717';
            buttoncolor= '#616161';
            $("body").css("background", mycolor);
            $("body").css("color", fontcolor);
            $(".boxbg").css("background", boxcolor);
            $(".buttonbg").css("background", buttoncolor);
            localStorage.setItem("colour", mycolor);
            localStorage.setItem("text-colour", fontcolor);
            localStorage.setItem("box",boxcolor);
            localStorage.setItem("button", buttoncolor);

        });
    });





</script>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Forlaugh
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    //<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  %body
    .jumbotron-fluid
      =render 'home/header'
      .container
        - flash.each do |name, msg|
          = content_tag(:div, msg, class: "alert alert-info")
      =yield
      =render 'home/footer'

app/views/posts/_form.html.erb
<%= form_for @post, html: {multipart:true} do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:" %>
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <div>
  <div class="form-group">
    <%= f.label "Description" %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image, "Image" %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit 'Save', class: "btn buttonbg middle-class" %>
  </div></div>
<% end %>

app/views/posts/edit.html.erb
<div class="middle-class margin-top box_nm boxbg table">
  <h3 class="middle-class">Editing post</h3>
<%= render 'form' %>
<%= button_to 'Show', @post, class:"btn middle-class margin-top margin-bottom buttonbg", :method => "get" %>
<%= button_to 'Back', posts_path, class:"btn middle-class margin-top margin-bottom buttonbg", :method => "get" %>
</div>

app/views/posts/index.html.erb
  <div class="rightclass sidebox boxbg">
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce malesuada sapien sit amet est pellentesque aliquam non at purus. Ut non auctor orci. Proin sed viverra quam. Aenean et odio eu nisl fringilla volutpat at eu enim. Nunc ac laoreet elit, nec placerat libero. Sed in purus id est varius laoreet. Proin luctus scelerisque ultrices. Aenean dolor purus, luctus sed mauris sed, vehicula rhoncus dui. Nulla feugiat diam ut accumsan interdum. Mauris vitae libero finibus, consequat nulla a, malesuada augue. Curabitur tellus erat, porttitor at metus sit amet, consectetur fringilla lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque mollis metus eu nulla suscipit fermentum. Etiam congue commodo euismod. Donec urna ex, mattis ac feugiat ac, sagittis imperdiet turpis.</p>
  </div>
<div id="posts" class="middle-class fixed">
    <% @posts.each do |post| %><br/>
      <div class="box boxbg">
        <div class="boximg">
        <%=link_to image_tag(post.image.url(:medium), :class => "image"), post %><br/>
        </div>
        <div class="center_text">
        <%= post.description %><br/>
        </div><br/>
        <%= simple_format "@#{post.user.name if post.user}"%><br/><br/>
        <div class="alignright">
          <div class="btnd floatright">
            <% if post.user == current_user %>
              <%= button_to 'Edit', edit_post_path(post), class:"btn buttonbg", :method => "get" %>
              <%= button_to 'Delete', post, class:"btn buttonbg leftmargin", :method => "delete", data: { confirm: 'Are you sure?' } %>
            <% end %>
          </div>
        </div>
        <div class="upvote_container">
        <div class="upvote_font">
        <%= post.plusminus %>
        </div>
        <%= link_to image_tag(("arrow.png"), :class => "upvotearrow"), vote_up_post_path(post), :method => :post, class: "leftmargin" %>
        <%= link_to image_tag(("undo.png"), :class => "upvotearrow"), vote_undo_post_path(post), :method => :post, class: "leftmargin" %>
        <%= link_to image_tag(("arrow.png"), :class => "downvotearrow"), vote_down_post_path(post), :method => :post, class: "leftmargin" %><br/><br/>
        </div>

      </div>
    <% end %>
<br/>
  <%= will_paginate @posts, renderer: WillPaginateInfinite::InfinitePagination %>
</div>

app/views/posts/new.html.erb
<div class="middle-class margin-top box_nm boxbg table">
  <h3 class="middle-class">New post</h3>
<%= render 'form' %>

<%= button_to 'Back', posts_path, class:"btn middle-class margin-top margin-bottom buttonbg", :method => "get" %>
</div>

app/views/posts/show.html.erb
<p id="notice">
  <%= notice %>
</p>
<div class="middle-class">
  <div class="L_box boxbg">
  <%= image_tag @post.image.url(:large), class:"image_show" %><br/>
  <b>Description:</b>
  <%= @post.description %><br/><%= simple_format "@#{@post.user.name}"%><br/><br/><br/>
    <div class="upvote_container">
      <div class="upvote_font">
        <%= @post.plusminus %>
      </div>
      <%= link_to image_tag(("arrow.png"), :class => "upvotearrow"), vote_up_post_path(@post), :method => :post, class: "leftmargin" %>
      <%= link_to image_tag(("undo.png"), :class => "upvotearrow"), vote_undo_post_path(@post), :method => :post, class: "leftmargin" %>
      <%= link_to image_tag(("arrow.png"), :class => "downvotearrow"), vote_down_post_path(@post), :method => :post, class: "leftmargin" %><br/><br/>
    </div>
    <div class="alignright">

      <div class="btnd floatright">
        <% if @post.user == current_user %>
          <%= button_to 'Edit', edit_post_path(@post), class:"btn buttonbg", :method => "get" %>
          <%= button_to 'Delete', @post, class:"btn buttonbg leftmargin", :method => "delete", data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
    </div>

    <%= button_to 'Back', posts_path, class:"btn buttonbg middle-class", :method => "get" %>
      </div>
</div>